/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface MarkdownRenderer {

    }
  }

  interface HTMLMarkdownRendererElement extends StencilComponents.MarkdownRenderer, HTMLStencilElement {}

  var HTMLMarkdownRendererElement: {
    prototype: HTMLMarkdownRendererElement;
    new (): HTMLMarkdownRendererElement;
  };
  interface HTMLElementTagNameMap {
    'markdown-renderer': HTMLMarkdownRendererElement;
  }
  interface ElementTagNameMap {
    'markdown-renderer': HTMLMarkdownRendererElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'markdown-renderer': JSXElements.MarkdownRendererAttributes;
    }
  }
  namespace JSXElements {
    export interface MarkdownRendererAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;